<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="bookstore">
    <!--Created XSD schema for bookstore XML validation-->

        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="book" maxOccurs="unbounded">

                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="author" type="xsd:string"/>
                            <xsd:element name="price" type="xsd:integer"/>

                        </xsd:sequence>
                    </xsd:complexType>

                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>

    </xsd:element>

</xsd:schema>